spring:
  redis:
    #SendBox(AWS)
    #host : arenaranking.k0mey4.ng.0001.apn2.cache.amazonaws.com
    #LIVE(AWS)
    host : cmolivesessionandleaderboard.0uh4cf.ng.0001.apn2.cache.amazonaws.com
    #local
    #host: localhost
    port: 6379
  profiles:
    active: live
#server:
#  compression:
#    enabled: true
#    mime-types: application/json
#    min-response-size: 1